"""Add SLA tracking fields to tickets

Revision ID: 1d24d97301fb
Revises: 044b0e513ce4
Create Date: 2026-09-11 17:09:09.575114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d24d97301fb'
down_revision: Union[str, Sequence[str], None] = '044b0e513ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_analysis_knowledge_base')
    op.add_column('tickets', sa.Column('sla_response_deadline', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('sla_resolution_deadline', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('sla_response_met', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('sla_resolution_met', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'sla_resolution_met')
    op.drop_column('tickets', 'sla_response_met')
    op.drop_column('tickets', 'sla_resolution_deadline')
    op.drop_column('tickets', 'sla_response_deadline')
    op.create_table('ai_analysis_knowledge_base',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('ai_analysis_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('knowledge_base_article_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ai_analysis_id'], ['ai_analyses.id'], name=op.f('ai_analysis_knowledge_base_ai_analysis_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_article_id'], ['knowledge_base_articles.id'], name=op.f('ai_analysis_knowledge_base_knowledge_base_article_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_analysis_knowledge_base_pkey'))
    )
    # ### end Alembic commands ###
