"""Add AI analysis knowledge base links

Revision ID: 45dcbbfe3640
Revises: 70987dc2bb03
Create Date: 2026-09-11 14:34:00.440613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45dcbbfe3640'
down_revision: Union[str, Sequence[str], None] = '70987dc2bb03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
