"""add ticket rating and feedback

Revision ID: c601604cec2f
Revises: 1873f47c29b1
Create Date: 2026-09-10 16:31:12.844560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c601604cec2f'
down_revision: Union[str, Sequence[str], None] = '1873f47c29b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'feedback')
    op.drop_column('tickets', 'rating')
    # ### end Alembic commands ###
